name: Build and Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache-
    - name: Install Dependencies
      run: |
        npm install --registry=https://registry.npm.taobao.org -g yarn
        yarn config set registry https://registry.npm.taobao.org
        yarn --frozen-lockfile --non-interactive
    - name: Lint
      run: |
        yarn lint
      env:
        CI: true
    - name: Build
      run: |
        yarn build
      env:
        PUBLIC_URL: "/cdot.network/"
        CI: true
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BASE_BRANCH: dev
        BRANCH: gh-pages
        FOLDER: dist
